name: Deploy

on:
  push:
    branches:
      - development # Changing the branch here would also work

jobs:
  build_client:
    runs-on: ubuntu-latest
    steps:
      - name: git
        run: |
          git subtree push --prefix client heroku main