name: Deploy

on:
  push:
    branches:
      - development # Changing the branch here would also work

jobs:
  build_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "client-steamengine" #Must be unique in Heroku
          heroku_email: "konrad.kowalczyk321@gmail.com"
  build_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "server-steamengine" #Must be unique in Heroku
          heroku_email: "konrad.kowalczyk321@gmail.com"