name: Deploy

on:
  push:
    branches:
      - development # Changing the branch here would also work

jobs:
  build_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          lfs: true
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: | 
          git subtree push --prefix client npm install
      - name: git
        run: |
          git subtree push --prefix client heroku main