name: Deploy

on:
  push:
    branches:
      - development # Changing the branch here would also work

jobs:
  build_client:
    runs-on: ubuntu-latest
    steps:
      - name: actions
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
          token: ${{ secrets.PAT }}
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: | 
          git subtree push --prefix client npm install
      - name: git
        run: |
          git subtree push --prefix client heroku main